# Auto-generated config for yggdra
# You can edit 'name', 'desc', 'type', 'click'. Do not change keys.
ASSETS = {
    "action_count.png": {
        "name": "行动次数",
        "desc": "",
        "type": "label",
        "click": "single",
    },
    "area_clear.png": {
        "name": "区域通关",
        "desc": "",
        "type": "button",
        "click": "single",
    },
    "award_text.png": {
        "name": "条件达成奖励",
        "desc": "",
        "type": "button",
        "click": "single",
    },
    "back.png": {"name": "返回", "desc": "", "type": "button", "click": "single"},
    "battle_again.png": {
        "name": "再次战斗",
        "desc": "",
        "type": "button",
        "click": "single",
    },
    "battle_prepare.png": {
        "name": "准备战斗",
        "desc": "",
        "type": "button",
        "click": "single",
    },
    "battle_start.png": {
        "name": "战斗开始",
        "desc": "",
        "type": "button",
        "click": "single",
    },
    "body.png": {"name": "人像", "desc": "", "type": "button", "click": "single"},
    "button_redeem.png": {
        "name": "Button Redeem",
        "desc": "",
        "type": "button",
        "click": "single",
    },
    "cancel.png": {"name": "取消", "desc": "", "type": "button", "click": "single"},
    "change_team.png": {
        "name": "队伍编成",
        "desc": "",
        "type": "button",
        "click": "single",
    },
    "chapter_arrow.png": {
        "name": "关卡箭头",
        "desc": "",
        "type": "button",
        "click": "single",
    },
    "claim_all.png": {
        "name": "全部领取",
        "desc": "",
        "type": "button",
        "click": "single",
    },
    "click_any_position.png": {
        "name": "点击任意位置关闭",
        "desc": "",
        "type": "button",
        "click": "single",
    },
    "click_close.png": {
        "name": "点击屏幕关闭",
        "desc": "",
        "type": "button",
        "click": "single",
    },
    "close.png": {"name": "关闭", "desc": "", "type": "button", "click": "single"},
    "equip_enforce.png": {
        "name": "装备强化",
        "desc": "",
        "type": "button",
        "click": "single",
    },
    "equip_select.png": {
        "name": "自动选择",
        "desc": "",
        "type": "button",
        "click": "single",
    },
    "head.png": {"name": "头像", "desc": "", "type": "button", "click": "single"},
    "label_max.png": {
        "name": "最大数量Max",
        "desc": "",
        "type": "button",
        "click": "single",
    },
    "levelup.png": {"name": "升级了", "desc": "", "type": "button", "click": "single"},
    "map_icon.png": {
        "name": "地图",
        "desc": "",
        "type": "button",
        "click": "single",
    },
    "my_team.png": {"name": "我的队伍", "desc": "", "type": "label", "click": "single"},
    "new_content.png": {
        "name": "新内容解锁",
        "desc": "",
        "type": "button",
        "click": "single",
    },
    "next_chapter.png": {
        "name": "下一个关卡",
        "desc": "",
        "type": "button",
        "click": "single",
    },
    "ok.png": {"name": "好的彩色", "desc": "", "type": "button", "click": "single"},
    "ok2.png": {"name": "好的灰色", "desc": "", "type": "button", "click": "single"},
    "redeem_confirm.png": {
        "name": "兑换确认",
        "desc": "",
        "type": "button",
        "click": "single",
    },
    "redeem_place.png": {
        "name": "兑换所",
        "desc": "",
        "type": "button",
        "click": "single",
    },
    "reedem_stone.png": {
        "name": "水晶",
        "desc": "",
        "type": "button",
        "click": "single",
    },
    "skip.png": {"name": "跳过Icon", "desc": "", "type": "button", "click": "single"},
    "stars.png": {"name": "星级Icon", "desc": "", "type": "button", "click": "single"},
    "wave.png": {"name": "波次Icon", "desc": "", "type": "button", "click": "single"},
    "win.png": {"name": "胜利Icon", "desc": "", "type": "button", "click": "single"},
}
